# setup gnocore basics
FROM golang:1.24-alpine AS setup-gnocore
ENV GNOROOT="/gnoroot"
ENV CGO_ENABLED=0 GOOS=linux
WORKDIR /gnoroot
RUN go env -w GOMODCACHE=/root/.cache/go-build
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod/,id=gomodcache \
    --mount=type=cache,target=/root/.cache/go-build,id=gobuildcache \
    go mod download -x
COPY . ./

# build gnoland binary
FROM setup-gnocore AS build-gnoland
RUN --mount=type=cache,target=/go/pkg/mod/,id=gomodcache \
    --mount=type=cache,target=/root/.cache/go-build,id=gobuildcache \
    go build -ldflags "-w -s" -o ./build/gnoland ./gno.land/cmd/gnoland

# final Gnoland image
FROM alpine:3 AS gnoland
WORKDIR /gnoroot
ENV GNOROOT="/gnoroot"
RUN apk add --no-cache ca-certificates
COPY --from=build-gnoland /gnoroot/build/gnoland                         /usr/bin/gnoland
COPY --from=build-gnoland /gnoroot/examples                              /gnoroot/examples
COPY --from=build-gnoland /gnoroot/gnovm/stdlibs                         /gnoroot/gnovm/stdlibs
COPY --from=build-gnoland /gnoroot/gnovm/tests/stdlibs                   /gnoroot/gnovm/tests/stdlibs
COPY --from=build-gnoland /gnoroot/gno.land/genesis/genesis_txs.jsonl    /gnoroot/gno.land/genesis/genesis_txs.jsonl
COPY --from=build-gnoland /gnoroot/gno.land/genesis/genesis_balances.txt /gnoroot/gno.land/genesis/genesis_balances.txt
EXPOSE 26656 26657
ENTRYPOINT ["/usr/bin/gnoland"]
